build:
  - prefect_docker.deployments.steps.build_docker_image:
      id: build-image
      requires: prefect-docker>=0.6.4
      image_name: lottery-pipeline-image
      tag: latest
      dockerfile: lottery/Dockerfile
      rm: true # remove intermediate containers

# known Prefect issue:
# prefect.deployments.steps.set_working_directory sometimes fails 
# with absolute paths (like /opt/prefect/lottery) even though the 
# directory exists in the built image.
# See https://github.com/PrefectHQ/prefect/issues/18182 for details.

# With this setup with worker as docker pool, prefer remote repo
pull:
  - prefect.deployments.steps.git_clone:
      repository: https://github.com/pessini/data-pipeline-blog.git
      # You ca use Prefect Blocks to load credentials in runtime
      # Ex: Block type github credentials with name gh-credentials
      # credentials: "{{ prefect.blocks.github-credentials.gh-credentials }}"

deployments:
  - name: extract-lottery-data
    version: "0.2"
    description: "Fetch lottery results and store in Minio"
    entrypoint: lottery/fetch_games_results.py:fetch_lottery_results
    schedule:
      - cron: "0 2 * * *" # every day at 2am
        slug: "daily-schedule"
        timezone: "America/Sao_Paulo"
        active: true
    parameters: 
      draw_number: null
    work_pool:
      name: docker
      job_variables:
        image: "{{ build-image.image }}"
    tags:
      - lottery
  
  - name: process-lottery-results
    version: "0.1"
    description: "Compile lottery results into DuckDB database and store in Minio"
    entrypoint: lottery/compile_lottery_results.py:compile_lottery_results
    work_pool:
      name: docker
      job_variables:
        image: "{{ build-image.image }}"
    tags:
      - lottery

  - name: reset-tags
    version: "0.1"
    description: "Flow to reset processed=true tags to processed=false."
    entrypoint: lottery/reset_processed_tags.py:reset_processed_tags
    work_pool:
      name: docker
      job_variables:
        image: "{{ build-image.image }}"
    tags:
      - lottery
